#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Parse arguments
SOURCE_TYPE=""
SOURCE_CONTENT=""
FORMAT="png"
WIDTH="794" # A4 Web Print Standard Width
HEIGHT="1123" # A4 Web Print Standard Height
FULL_PAGE="false"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --source_type) SOURCE_TYPE="$2"; shift ;;
        --source_content) SOURCE_CONTENT="$2"; shift ;;
        --format) FORMAT="$2"; shift ;;
        --width) WIDTH="$2"; shift ;;
        --height) HEIGHT="$2"; shift ;;
        --full_page) FULL_PAGE="true"; ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Validate required inputs
if [ -z "$SOURCE_TYPE" ] || [ -z "$SOURCE_CONTENT" ]; then
    echo '{"status": "error", "message": "Missing required arguments: --source_type and --source_content"}'
    exit 1
fi

# Prepare output directory
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_DIR="$(pwd)/output"
mkdir -p "$OUTPUT_DIR"
OUTPUT_PATH="${OUTPUT_DIR}/rendered_${TIMESTAMP}.${FORMAT}"

# Determine target URL
TARGET_URL=""
TMP_HTML=""

if [ "$SOURCE_TYPE" = "url" ]; then
    TARGET_URL="$SOURCE_CONTENT"
elif [ "$SOURCE_TYPE" = "file" ]; then
    # Ensure it's an absolute path for file://
    if [[ "$SOURCE_CONTENT" = /* ]]; then
         TARGET_URL="file://${SOURCE_CONTENT}"
    else
         TARGET_URL="file://$(pwd)/${SOURCE_CONTENT}"
    fi
elif [ "$SOURCE_TYPE" = "code" ]; then
    TMP_HTML=$(mktemp /tmp/html_to_image_XXXXXX.html)
    cat > "$TMP_HTML" <<EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            background: white;
            /* Hide overflow to prevent scrollbars from generating whitespace */
            overflow: hidden;
            width: fit-content;
            height: fit-content;
        }
    </style>
</head>
<body>
$SOURCE_CONTENT
</body>
</html>
EOF
    TARGET_URL="file://${TMP_HTML}"
else
    echo '{"status": "error", "message": "Invalid source_type. Must be url, file, or code."}'
    exit 1
fi

# Ensure Ghostscript is installed
if ! command -v gs &> /dev/null; then
    echo '{"status": "error", "message": "Ghostscript (gs) is required but not installed on this system."}'
    exit 1
fi

# Step 1: Generate PDF using Playwright (Provides Native Print Media Emulation)
TMP_PDF=$(mktemp /tmp/html_to_image_XXXXXX.pdf)

PLAYWRIGHT_CMD="npx --yes playwright pdf \"$TARGET_URL\" \"$TMP_PDF\""
eval "$PLAYWRIGHT_CMD" > /dev/null 2>&1

if [ $? -ne 0 ]; then
    echo '{"status": "error", "message": "Failed to generate print layout PDF."}'
    [ -n "$TMP_HTML" ] && rm -f "$TMP_HTML"
    rm -f "$TMP_PDF"
    exit 1
fi

# Step 2: Use Ghostscript to rasterize the PDF into High-DPI PNGs
BASENAME=$(basename "$OUTPUT_PATH")
DIRNAME=$(dirname "$OUTPUT_PATH")
EXT="${BASENAME##*.}"
NAME="${BASENAME%.*}"

# Outputs to <output_path_page1.png>, <output_path_page2.png>
GS_OUTPUT_STUB="${DIRNAME}/${NAME}_page%d.${EXT}"

GS_CMD="gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r300 -sOutputFile=\"$GS_OUTPUT_STUB\" \"$TMP_PDF\""
eval "$GS_CMD" > /dev/null 2>&1

if [ $? -ne 0 ]; then
    echo '{"status": "error", "message": "Ghostscript failed to rasterize the PDF into images."}'
    [ -n "$TMP_HTML" ] && rm -f "$TMP_HTML"
    rm -f "$TMP_PDF"
    exit 1
fi

# Step 3: Collect generated images
GENERATED_FILES=()

# Find all generated files matching the pattern
for file in "${DIRNAME}/${NAME}_page"*.${EXT}; do
    if [ -f "$file" ]; then
        GENERATED_FILES+=("\"$file\"")
    fi
done

PAGES=${#GENERATED_FILES[@]}

# If somehow 0 pages, fail
if [ "$PAGES" -eq 0 ]; then
    echo '{"status": "error", "message": "No images were generated by Ghostscript."}'
    [ -n "$TMP_HTML" ] && rm -f "$TMP_HTML"
    rm -f "$TMP_PDF"
    exit 1
fi

FILES_JSON=$(IFS=,; echo "[${GENERATED_FILES[*]}]")

# Cleanup temporary files
[ -n "$TMP_HTML" ] && rm -f "$TMP_HTML" || true
rm -f "$TMP_PDF" || true

# Output standard JSON
cat <<EOF
{
  "status": "success",
  "message": "Generated $PAGES high-quality images via Playwright PDF and Ghostscript.",
  "data": {
    "output_paths": $FILES_JSON,
    "format": "$FORMAT",
    "source_type": "$SOURCE_TYPE",
    "pages": $PAGES
  }
}
EOF

